Repository owncloud/openidconnect, pull requests merged in 2020-04, with the labels that each got.

#69 Updating phpseclib/phpseclib (2.0.25 => 2.0.27)
  composer.lock
Labels: 3 - To Review, QA-team, dependencies

#73 Use upstream jumbojett/openid-connect-php@0.9.0
  composer.json
  composer.lock
  phpstan.neon
Labels: 3 - To Review

#75 [Tests-Only] Bump phan 2.7
  lib/LoginPageBehaviour.php
  vendor-bin/phan/composer.json
Labels: 3 - To Review, QA-team

#79 Adjust test to php 7.4
  .drone.star
  .gitignore
  lib/SessionVerifier.php
Labels: 3 - To Review
